# Generated by Django 2.2.1 on 2019-06-22 00:49

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('CONSULTING', 'Consulting'), ('CELEBRITY', 'Celebrity'), ('CONTRACT', 'Contract'), ('MEDIA', 'Media'), ('ELECTRONICS', 'Electronics'), ('ENTERTAINMENT', 'Entertainment'), ('INFORMATION', 'Information Technology'), ('OTHERS', 'Others')], default='OTHERS', max_length=50, null=True)),
                ('official_business_name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, default='', editable=True, null=True, populate_from='official_business_name', unique_with=['user'])),
                ('prefered_language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en-us', max_length=10)),
                ('rated', models.IntegerField(null=True)),
                ('views', models.IntegerField(null=True)),
                ('country_origin', django_countries.fields.CountryField(default='--select country--', max_length=2)),
                ('country_city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('office_phone', models.IntegerField(blank=True, default=0)),
                ('contact_cell', models.IntegerField(blank=True, default=0)),
                ('email_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('support_email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sales_email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('info_email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('about', models.TextField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('update_ip_addres', models.GenericIPAddressField(default='127.0.0.1')),
                ('viewed_by', models.GenericIPAddressField(default='127.0.0.1')),
                ('website', models.URLField(blank=True, null=True)),
                ('other_website', models.URLField(blank=True, null=True)),
                ('blog', models.URLField(blank=True, null=True)),
                ('other_names', models.CharField(blank=True, default='', max_length=50)),
                ('company_name', models.CharField(blank=True, default='', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/profile_image')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/cover_cover')),
                ('about_video', models.FileField(blank=True, null=True, upload_to='videos/about_video')),
                ('who_we_are_video', models.FileField(blank=True, null=True, upload_to='videos/who_we_are_video')),
                ('services_video', models.FileField(blank=True, null=True, upload_to='videos/services_video')),
                ('projects_video', models.FileField(blank=True, null=True, upload_to='videos/projects_video')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(blank=True, related_name='profile_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
