# Generated by Django 2.2.1 on 2019-06-22 01:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
