# Generated by Django 2.2.1 on 2019-06-22 00:49

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_tittle', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='job_tittle', unique_with=['user', 'created'])),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('job_type', models.CharField(choices=[('F', 'Full time'), ('P', 'Part time'), ('C', 'Contract'), ('L', 'Freelancer'), ('I', 'Internship'), ('V', 'Volunteer')], default='F', max_length=1)),
                ('location', models.CharField(choices=[('O', 'Office'), ('R', 'Remote')], default='O', max_length=15)),
                ('job_video', models.FileField(blank=True, null=True, upload_to='videos/jobs/job_video')),
                ('rating', models.FloatField(null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('view_by', models.GenericIPAddressField(default='127.0.0.1')),
                ('deleted', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('min_salary', models.FloatField(default=150.0)),
                ('max_salary', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(null=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', '-last_edited'),
            },
        ),
    ]
