# Generated by Django 2.2.1 on 2019-06-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='view_by',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
