# Generated by Django 2.2.2 on 2019-06-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_repostjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repostjob',
            old_name='job_video',
            new_name='job_image',
        ),
    ]
