# Generated by Django 2.2.2 on 2019-06-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190629_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='job_type',
            field=models.CharField(choices=[('F', 'Full time'), ('P', 'Part time'), ('C', 'Contract'), ('L', 'Freelancer'), ('I', 'Internship'), ('V', 'Volunteer')], default='F', max_length=50),
        ),
        migrations.AlterField(
            model_name='repostjob',
            name='job_type',
            field=models.CharField(choices=[('F', 'Full time'), ('P', 'Part time'), ('C', 'Contract'), ('L', 'Freelancer'), ('I', 'Internship'), ('V', 'Volunteer')], default='F', max_length=50),
        ),
    ]
