# Generated by Django 2.2.2 on 2019-07-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190630_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='view_by',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
