"""
Django settings for gettingstarted project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
#import django_heroku
import dj_database_url
from decouple import config


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ['pervasivetest.herokuapp.com', '127.0.0.1', '[::1]', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'ckeditor',
    'ckeditor_uploader',

    'django.forms',


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',


    #third party-django dependencies
    'rest_framework',
    'django_countries',
    #'django_hosts',

    #BASECODE project apps
    'django_sb_admin',
    'pervasive',
    'accounts',
    'newsletter',
    'profiles',
    'finance',
    'search',
    #'watermarker',

    #ADMANAGER APPS
    'blog',
    'jobs',
    'adclass',
    'products',
    'services',
    'drive',
    'recycle',
    'support',

    'flock',
    'settings',
    'utilities',
    'home',

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "basecode.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR + '/templates/'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                #media handler
                'django.template.context_processors.media',
            ],
            #templatetags
            'libraries':{
            'class_name'            : 'search.templatetags.class_name',
            'product_n_services'    : 'pervasive.templatetags.product_n_services',
            'jobs_tag'              : 'jobs.templatetags.jobs_tag',

            }
        },
    }
]

TEMPLATE_LOADERS = (
    'django.template.loaders.app_directories.load_template_source',
)


WSGI_APPLICATION = "basecode.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE" : "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3")
    }
}
ADMINS = (
    ('Mr Lebeus', 'lebeusm@yahoo.com'),
)

MANAGERS = ADMINS

DEBUG = True
#TEMPLATE_DEBUG = DEBUG

# # DEBUG404 = True
# #
SECRET_KEY = "CHANGE_ME!!!! (P.S. the SECRET_KEY environment variable will be used, if set, instead)."


# SECRET_KEY = config('SECRET_KEY')
#SENDGRID_API_KEY = config('SENDGRID_API_KEY')
#SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY')
# DEBUG = config('DEBUG', default=True, cast=bool)
# DATABASES = {
#     'default': dj_database_url.config(
#          default=config('DATABASE_URL')
#     )
# }

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_REDIRECT_URL              = '/flock/'
LOGIN_URL                       = '/account/login/'
LOGOUT_REDIRECT_URL = '/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#STATICFILES_DIRS = [ STATIC_ROOT, ]
MEDIA_URL                       = '/media/'
MEDIA_ROOT                      = os.path.join(BASE_DIR, 'basecode/media')
#MEDIA_ROOT                      = os.path.join(BASE_DIR, 'media')



SENDGRID_API_KEY = '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'

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# #EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_HOST_USER = 'apikey'
# EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = '<noreply@basecodenam.com>'



# CORS_REPLACE_HTTPS_REFERER      = True
# HOST_SCHEME                     = "https://"
# SECURE_PROXY_SSL_HEADER         = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT             = True
# SESSION_COOKIE_SECURE           = True
# CSRF_COOKIE_SECURE              = True
# SECURE_HSTS_INCLUDE_SUBDOMAINS  = True
# SECURE_HSTS_SECONDS             = 1000000
# SECURE_FRAME_DENY               = True




#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'brainwave90@gmail.com'
EMAIL_HOST_PASSWORD = '90052000'
DEFAULT_FROM_EMAIL = 'noreply@support.basecode.com'
#DEFAULT_TO_EMAIL = ''


#...
SITE_ID = 1

####################################
    ##  CKEDITOR CONFIGURATION ##
####################################

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"


CKEDITOR_ALLOW_NONIMAGE_FILES = True
#X_FRAME_OPTIONS = 'SAMEORIGIN'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar'   : 'full',
        'width': 'auto',
        'height': 'auto',
        #'skin': 'moono',
    },
}



# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
# AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
# AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
# AWS_QUERYSTRING_AUTH = False
# AWS_S3_CUSTOM_DOMAIN = os.environ.get("AWS_S3_CUSTOM_DOMAIN", "")
# MEDIA_ROOT = os.environ.get("MEDIA_URL", "")
# MEDIA_URL = '/media/'
#django_heroku.settings(locals())
