# Generated by Django 2.2.2 on 2019-06-25 11:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190622_0108'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0003_post_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostMail',
        ),
        migrations.RenameField(
            model_name='postmail',
            old_name='title',
            new_name='tittle',
        ),
    ]
