# Generated by Django 2.2.2 on 2019-07-02 23:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20190702_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmail',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='tittle', unique_with=['user', 'created']),
        ),
    ]
