# Generated by Django 2.2.2 on 2019-07-03 00:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20190702_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmail',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='postmail',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postmail',
            name='body',
        ),
        migrations.RemoveField(
            model_name='postmail',
            name='number_of_click',
        ),
        migrations.RemoveField(
            model_name='postmail',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='postmail',
            name='status',
        ),
        migrations.AddField(
            model_name='postmail',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
    ]
