# Generated by Django 2.2.2 on 2019-07-03 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20190703_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
