# Generated by Django 2.2.1 on 2019-06-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultimg',
            old_name='default_img',
            new_name='basecode_logo',
        ),
        migrations.RemoveField(
            model_name='defaultimg',
            name='user',
        ),
        migrations.AddField(
            model_name='defaultimg',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/defaults'),
        ),
        migrations.AddField(
            model_name='defaultimg',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/defaults'),
        ),
        migrations.AddField(
            model_name='defaultimg',
            name='jobs_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/defaults'),
        ),
        migrations.AddField(
            model_name='defaultimg',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/defaults'),
        ),
        migrations.AddField(
            model_name='defaultimg',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/defaults'),
        ),
        migrations.AddField(
            model_name='defaultimg',
            name='service_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/defaults'),
        ),
        migrations.AddField(
            model_name='defaultimg',
            name='tender_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/defaults'),
        ),
    ]
