# Generated by Django 2.2.1 on 2019-05-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_type',
            field=models.CharField(choices=[('T', 'Technical'), ('PL', 'Plans'), ('S', 'Security'), ('D', 'Design'), ('A', 'Adverts'), ('P', 'Profile/ Account'), ('O', 'Others')], default='T', max_length=1),
        ),
    ]
