# Generated by Django 2.2.1 on 2019-06-22 00:49

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_file', models.FileField(blank=True, null=True, upload_to='uploads/docs/tender_doc_files')),
                ('solution_video', models.FileField(blank=True, null=True, upload_to='uploads/docs/solution_video')),
                ('similar_work_video', models.FileField(blank=True, null=True, upload_to='videos/docs/similar_tender_video')),
                ('times_viewed', models.IntegerField(blank=True, default=0, null=True)),
                ('seen', models.GenericIPAddressField(default='127.0.0.1')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_tittle', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='tender_tittle', unique_with=['user', 'created'])),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('advtised_before', models.BooleanField(default=False)),
                ('tender_video', models.FileField(blank=True, null=True, upload_to='videos/adclass/tender_video')),
                ('contact_person_name', models.CharField(default='', max_length=500)),
                ('office_no', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=255)),
                ('levy_price', models.FloatField(default=500, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('view_by', models.GenericIPAddressField(default='127.0.0.1')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('edited', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('required_docs', models.TextField(max_length=140)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='tittle', unique_with=['user', 'created'])),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('view_by', models.GenericIPAddressField(default='127.0.0.1')),
                ('country', django_countries.fields.CountryField(default='--select--', max_length=2)),
                ('city', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('edited', models.BooleanField(default=False)),
                ('applicants', models.ManyToManyField(related_name='applicants', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_tittle', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='announce_tittle', unique_with=['user', 'created'])),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('announce_type', models.CharField(choices=[('E', 'Expression of interest'), ('EV', 'Event'), ('B', 'Bid'), ('N', 'News')], default='EV', max_length=50)),
                ('announce_image', models.FileField(blank=True, null=True, upload_to='images/announce/announce_image')),
                ('rating', models.FloatField(null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('view_by', models.GenericIPAddressField(default='127.0.0.1')),
                ('deleted', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(null=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', '-last_edited'),
            },
        ),
    ]
